<?php include('header.phtml'); ?>
<h1>Cars</h1>

<table id="Cars">
    <thead>
        <tr>
            <td>Make</td>
            <td>Model</td>
            <td>Price</td>
            <td>Mileage</td>
        </tr>
</table>

<script type="text/javascript">
 $(function() {
     $.getJSON('<?php echo $targetUrl; ?>', function(result){
         $.each(result, function(i, car){
             $('#Cars').append('<tr><td>'+car.make+'</td><td>'+car.model+'</td><td class="number">$'+$.number(car.price)+'</td><td class="number">'+$.number(car.mileage)+'</td></tr>');
         });
     });
 });
</script>
<?php include('footer.phtml'); ?>
