<!DOCTYPE html>
<html>
    <head>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript" />
         <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="/assets/style.css" />
        <script src="/assets/jquery-number.js" type="text/javascript"></script>
        <title>Sample Project - Matt Belanger</title>
    </head>
    <body>
        <div class="container">
            <header>
                <nav>
                    <a class="nav" href="/">Home</a>
                    <?php if(User::isLoggedIn()) {  ?>
                    <a class="nav" href="/hondas">Hondas Only</a>
                    <a class="nav" href="/logout">Logout</a>
                    <?php } else { ?>
                    <a class="nav" href="/login">Login</a>
                    <?php }  ?>
                    <a class="nav" href="/tests.php">Show Unit Tests</a>
            </header>
